name: "Scrape and Extract #crypticclueaday"

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "17 17 * * 6"

jobs:
  scrape-and-extract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Scrape tweets
      env:
        TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}
      run: |
        python scrape.py
    - name: Deduplicate tweets
      run: |
        sort -u raw_tweets.jsonl -o raw_tweets.jsonl
    - name: Extract clues and explanations
      run: |
        python extract.py
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
